### ISSUE TITLE
Opening an existing session for a directory doesn't remember/reload NerdTree

### ISSUE THREAD

**Issue by mtrx1337** [isaacmorneau/vim-simple-sessions#1]
# What I tried to do

My current session had NerdTree and a few other buffers open. I wanted to save that session with `:Smk`. When re-opening nvim in the same directory, NerdTree showed up as an empty buffer. When re-opening NerdTree through my :NERDTreeToggle keybind, another NerdTree split opened and both NerdTree suddenly showed up, resulting in 2 NerdTree buffers.

# what?
[Here's a video.](https://youtu.be/nEGoFNVjPF8)

**Comment by isaacmorneau** [comment]
https://stackoverflow.com/questions/4226905/vim-nerdtree-not-recovered-in-session-restore
looks like NERDTree just doesn't play well with sessions. I'll check for and close them before creating or updating sessions.

**Comment by isaacmorneau** [comment]
That does it, it closes it if it exists before saving a session
